# Spring Datasource Configuration
spring:
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restaurant?serverTimezone=Asia/Seoul
    username: root
    password: 6298


  # JPA Configuration
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect


logging:
  file:
    name: application.log
  level:
    org.springframework: INFO
    com.yourpackage: DEBUG
